version = 1

test_patterns = ["src/NHibernate.Test/**"]

exclude_patterns = [
  "src/NHibernate/Async/**/*.cs",
  "src/NHibernate.DomainModel/Async/**/*.cs"
  "src/NHibernate.Test/Async/**/*.cs"
]

[[analyzers]]
name = "csharp"
enabled = true
