dist: trusty
language: csharp
mono: none
dotnet: 2.1.300
sudo: required
services:
  - mysql
  - postgresql
  - docker
env:
  - DB=SqlServer2008 CONNECTION_STRING="Server=localhost;initial catalog=nhibernate;User Id=sa;Password=P@ssw0rd;packet size=4096;"
  - DB=PostgreSQL CONNECTION_STRING="Host=localhost;Port=5432;Username=postgres;Database=nhibernate;Enlist=true;"
  - DB=Firebird 
  - DB=MySQL CONNECTION_STRING="Server=127.0.0.1;Uid=root;Database=nhibernate;Old Guids=True;"   
  - DB=SQLite 
before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update -qq
  - sudo apt-get install -y powershell 
  - |-
    if [[ "$DB" == "MySQL" ]]
    then
      echo -e '[server]\nlower_case_table_names=1' | sudo tee -a /etc/mysql/my.cnf
      sudo service mysql restart
    fi
  - |-
    if [[ "$DB" == "Firebird" ]]
    then
      sudo apt-get install -y libicu-dev libtommath-dev curl
      curl -L -O https://github.com/FirebirdSQL/firebird/releases/download/R3_0_5/Firebird-3.0.5.33220-0.amd64.tar.gz
      tar xzvf Firebird-3.0.5.33220-0.amd64.tar.gz
      pushd Firebird-3.0.5.33220-0.amd64
        sudo ./install.sh -silent   
      popd
      export $(sudo cat /opt/firebird/SYSDBA.password | grep -v ^# | xargs)
      sudo chmod 775 /tmp/firebird
      echo -e "nhibernate = /tmp/firebird/nhibernate.fdb" | sudo tee -a /opt/firebird/databases.conf
      echo -e "AuthServer = Srp\nAuthClient = Srp\nUserManager = Srp\nWireCrypt = Enabled" | sudo tee -a /opt/firebird/firebird.conf
      sudo /opt/firebird/bin/gsec -modify SYSDBA -pw masterkey -admin yes
      sudo service firebird restart
    fi
before_script:
  - if [[ "$DB" == "SqlServer2008" ]]; then docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "MSSQL_PID=Express" -p 1433:1433 -d --name sqlexpress microsoft/mssql-server-linux:latest; fi
  - if [[ "$DB" == "PostgreSQL" ]]; then psql -c "CREATE DATABASE nhibernate;" -U postgres; fi
  - if [[ "$DB" == "MySQL" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS nhibernate;"; fi
script:
  - pwsh -noprofile -command "& ./build.ps1 -TaskList Set-Configuration,Test -properties @{\"Database\" = \"$DB\";\"ConnectionString\"=\"$CONNECTION_STRING\"}"
